[package]
name = "optur"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.1.0"
prost = "0.9.0"
prost-types = "0.9.0"
rand = "0.8.4"

[build-dependencies]
prost-build = "0.9.0"
