# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: optur/proto/sampler.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="optur/proto/sampler.proto",
    package="optur",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x19optur/proto/sampler.proto\x12\x05optur"\x0f\n\rSamplerConfigb\x06proto3',
)


_SAMPLERCONFIG = _descriptor.Descriptor(
    name="SamplerConfig",
    full_name="optur.SamplerConfig",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=36,
    serialized_end=51,
)

DESCRIPTOR.message_types_by_name["SamplerConfig"] = _SAMPLERCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SamplerConfig = _reflection.GeneratedProtocolMessageType(
    "SamplerConfig",
    (_message.Message,),
    {
        "DESCRIPTOR": _SAMPLERCONFIG,
        "__module__": "optur.proto.sampler_pb2"
        # @@protoc_insertion_point(class_scope:optur.SamplerConfig)
    },
)
_sym_db.RegisterMessage(SamplerConfig)


# @@protoc_insertion_point(module_scope)
