# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)
from google.protobuf.descriptor import (
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)
from google.protobuf.message import Message as google___protobuf___message___Message

DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class SamplerConfig(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    def __init__(
        self,
    ) -> None: ...

type___SamplerConfig = SamplerConfig
