# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from typing import Iterable as typing___Iterable
from typing import Mapping as typing___Mapping
from typing import MutableMapping as typing___MutableMapping
from typing import Optional as typing___Optional
from typing import Text as typing___Text

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)
from google.protobuf.descriptor import (
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)
from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)
from google.protobuf.message import Message as google___protobuf___message___Message
from typing_extensions import Literal as typing_extensions___Literal

builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int

DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class ParameterValue(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    int_value: builtin___int = ...
    double_value: builtin___float = ...
    string_value: typing___Text = ...
    def __init__(
        self,
        *,
        int_value: typing___Optional[builtin___int] = None,
        double_value: typing___Optional[builtin___float] = None,
        string_value: typing___Optional[typing___Text] = None,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions___Literal[
            "double_value",
            b"double_value",
            "int_value",
            b"int_value",
            "string_value",
            b"string_value",
            "value",
            b"value",
        ],
    ) -> builtin___bool: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal[
            "double_value",
            b"double_value",
            "int_value",
            b"int_value",
            "string_value",
            b"string_value",
            "value",
            b"value",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing_extensions___Literal["value", b"value"]
    ) -> typing_extensions___Literal["int_value", "double_value", "string_value"]: ...

type___ParameterValue = ParameterValue

class Distribution(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class FloatDistribution(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        low: builtin___float = ...
        high: builtin___float = ...
        log_scale: builtin___bool = ...
        def __init__(
            self,
            *,
            low: typing___Optional[builtin___float] = None,
            high: typing___Optional[builtin___float] = None,
            log_scale: typing___Optional[builtin___bool] = None,
        ) -> None: ...
        def ClearField(
            self,
            field_name: typing_extensions___Literal[
                "high", b"high", "log_scale", b"log_scale", "low", b"low"
            ],
        ) -> None: ...
    type___FloatDistribution = FloatDistribution
    class IntDistribution(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        low: builtin___int = ...
        high: builtin___int = ...
        log_scale: builtin___bool = ...
        def __init__(
            self,
            *,
            low: typing___Optional[builtin___int] = None,
            high: typing___Optional[builtin___int] = None,
            log_scale: typing___Optional[builtin___bool] = None,
        ) -> None: ...
        def ClearField(
            self,
            field_name: typing_extensions___Literal[
                "high", b"high", "log_scale", b"log_scale", "low", b"low"
            ],
        ) -> None: ...
    type___IntDistribution = IntDistribution
    class CategoricalDistribution(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        @property
        def choices(
            self,
        ) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[
            type___ParameterValue
        ]: ...
        def __init__(
            self,
            *,
            choices: typing___Optional[typing___Iterable[type___ParameterValue]] = None,
        ) -> None: ...
        def ClearField(
            self, field_name: typing_extensions___Literal["choices", b"choices"]
        ) -> None: ...
    type___CategoricalDistribution = CategoricalDistribution
    class FixedDistribution(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        @property
        def value(self) -> type___ParameterValue: ...
        def __init__(
            self,
            *,
            value: typing___Optional[type___ParameterValue] = None,
        ) -> None: ...
        def HasField(
            self, field_name: typing_extensions___Literal["value", b"value"]
        ) -> builtin___bool: ...
        def ClearField(
            self, field_name: typing_extensions___Literal["value", b"value"]
        ) -> None: ...
    type___FixedDistribution = FixedDistribution
    class UnknownDistribution(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        @property
        def values(
            self,
        ) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[
            type___ParameterValue
        ]: ...
        def __init__(
            self,
            *,
            values: typing___Optional[typing___Iterable[type___ParameterValue]] = None,
        ) -> None: ...
        def ClearField(
            self, field_name: typing_extensions___Literal["values", b"values"]
        ) -> None: ...
    type___UnknownDistribution = UnknownDistribution
    @property
    def unknown_distribution(self) -> type___Distribution.UnknownDistribution: ...
    @property
    def float_distribution(self) -> type___Distribution.FloatDistribution: ...
    @property
    def int_distribution(self) -> type___Distribution.IntDistribution: ...
    @property
    def categorical_distribution(self) -> type___Distribution.CategoricalDistribution: ...
    @property
    def fixed_distribution(self) -> type___Distribution.FixedDistribution: ...
    def __init__(
        self,
        *,
        unknown_distribution: typing___Optional[type___Distribution.UnknownDistribution] = None,
        float_distribution: typing___Optional[type___Distribution.FloatDistribution] = None,
        int_distribution: typing___Optional[type___Distribution.IntDistribution] = None,
        categorical_distribution: typing___Optional[
            type___Distribution.CategoricalDistribution
        ] = None,
        fixed_distribution: typing___Optional[type___Distribution.FixedDistribution] = None,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions___Literal[
            "categorical_distribution",
            b"categorical_distribution",
            "distribution",
            b"distribution",
            "fixed_distribution",
            b"fixed_distribution",
            "float_distribution",
            b"float_distribution",
            "int_distribution",
            b"int_distribution",
            "unknown_distribution",
            b"unknown_distribution",
        ],
    ) -> builtin___bool: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal[
            "categorical_distribution",
            b"categorical_distribution",
            "distribution",
            b"distribution",
            "fixed_distribution",
            b"fixed_distribution",
            "float_distribution",
            b"float_distribution",
            "int_distribution",
            b"int_distribution",
            "unknown_distribution",
            b"unknown_distribution",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing_extensions___Literal["distribution", b"distribution"]
    ) -> typing_extensions___Literal[
        "unknown_distribution",
        "float_distribution",
        "int_distribution",
        "categorical_distribution",
        "fixed_distribution",
    ]: ...

type___Distribution = Distribution

class SearchSpace(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class DistributionsEntry(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        key: typing___Text = ...
        @property
        def value(self) -> type___Distribution: ...
        def __init__(
            self,
            *,
            key: typing___Optional[typing___Text] = None,
            value: typing___Optional[type___Distribution] = None,
        ) -> None: ...
        def HasField(
            self, field_name: typing_extensions___Literal["value", b"value"]
        ) -> builtin___bool: ...
        def ClearField(
            self, field_name: typing_extensions___Literal["key", b"key", "value", b"value"]
        ) -> None: ...
    type___DistributionsEntry = DistributionsEntry
    @property
    def distributions(self) -> typing___MutableMapping[typing___Text, type___Distribution]: ...
    def __init__(
        self,
        *,
        distributions: typing___Optional[
            typing___Mapping[typing___Text, type___Distribution]
        ] = None,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions___Literal["distributions", b"distributions"]
    ) -> None: ...

type___SearchSpace = SearchSpace

class Observation(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class ParametersEntry(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        key: typing___Text = ...
        @property
        def value(self) -> type___ParameterValue: ...
        def __init__(
            self,
            *,
            key: typing___Optional[typing___Text] = None,
            value: typing___Optional[type___ParameterValue] = None,
        ) -> None: ...
        def HasField(
            self, field_name: typing_extensions___Literal["value", b"value"]
        ) -> builtin___bool: ...
        def ClearField(
            self, field_name: typing_extensions___Literal["key", b"key", "value", b"value"]
        ) -> None: ...
    type___ParametersEntry = ParametersEntry
    @property
    def parameters(self) -> typing___MutableMapping[typing___Text, type___ParameterValue]: ...
    def __init__(
        self,
        *,
        parameters: typing___Optional[
            typing___Mapping[typing___Text, type___ParameterValue]
        ] = None,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions___Literal["parameters", b"parameters"]
    ) -> None: ...

type___Observation = Observation
