# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from typing import Iterable as typing___Iterable
from typing import Optional as typing___Optional
from typing import Text as typing___Text

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)
from google.protobuf.descriptor import (
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)
from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)
from google.protobuf.message import Message as google___protobuf___message___Message
from google.protobuf.timestamp_pb2 import (
    Timestamp as google___protobuf___timestamp_pb2___Timestamp,
)
from typing_extensions import Literal as typing_extensions___Literal

from optur.proto.study_pb2 import StudyInfo as optur___proto___study_pb2___StudyInfo
from optur.proto.study_pb2 import Trial as optur___proto___study_pb2___Trial

builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int

DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class Request(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    stop: builtin___bool = ...
    thread_id: builtin___int = ...
    @property
    def get_current_timestamp(self) -> type___GetCurrentTimestampRequest: ...
    @property
    def get_studies(self) -> type___GetStudiesRequest: ...
    @property
    def get_trials(self) -> type___GetTrialsRequest: ...
    @property
    def get_trial(self) -> type___GetTrialRequest: ...
    @property
    def write_study(self) -> type___WriteStudyRequest: ...
    @property
    def write_trial(self) -> type___WriteTrialRequest: ...
    def __init__(
        self,
        *,
        get_current_timestamp: typing___Optional[type___GetCurrentTimestampRequest] = None,
        get_studies: typing___Optional[type___GetStudiesRequest] = None,
        get_trials: typing___Optional[type___GetTrialsRequest] = None,
        get_trial: typing___Optional[type___GetTrialRequest] = None,
        write_study: typing___Optional[type___WriteStudyRequest] = None,
        write_trial: typing___Optional[type___WriteTrialRequest] = None,
        stop: typing___Optional[builtin___bool] = None,
        thread_id: typing___Optional[builtin___int] = None,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions___Literal[
            "get_current_timestamp",
            b"get_current_timestamp",
            "get_studies",
            b"get_studies",
            "get_trial",
            b"get_trial",
            "get_trials",
            b"get_trials",
            "request",
            b"request",
            "stop",
            b"stop",
            "write_study",
            b"write_study",
            "write_trial",
            b"write_trial",
        ],
    ) -> builtin___bool: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal[
            "get_current_timestamp",
            b"get_current_timestamp",
            "get_studies",
            b"get_studies",
            "get_trial",
            b"get_trial",
            "get_trials",
            b"get_trials",
            "request",
            b"request",
            "stop",
            b"stop",
            "thread_id",
            b"thread_id",
            "write_study",
            b"write_study",
            "write_trial",
            b"write_trial",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing_extensions___Literal["request", b"request"]
    ) -> typing_extensions___Literal[
        "get_current_timestamp",
        "get_studies",
        "get_trials",
        "get_trial",
        "write_study",
        "write_trial",
        "stop",
    ]: ...

type___Request = Request

class Reply(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    @property
    def get_current_timestamp(self) -> type___GetCurrentTimestampReply: ...
    @property
    def get_studies(self) -> type___GetStudiesReply: ...
    @property
    def get_trials(self) -> type___GetTrialsReply: ...
    @property
    def get_trial(self) -> type___GetTrialReply: ...
    @property
    def write_study(self) -> type___WriteStudyReply: ...
    @property
    def write_trial(self) -> type___WriteTrialReply: ...
    def __init__(
        self,
        *,
        get_current_timestamp: typing___Optional[type___GetCurrentTimestampReply] = None,
        get_studies: typing___Optional[type___GetStudiesReply] = None,
        get_trials: typing___Optional[type___GetTrialsReply] = None,
        get_trial: typing___Optional[type___GetTrialReply] = None,
        write_study: typing___Optional[type___WriteStudyReply] = None,
        write_trial: typing___Optional[type___WriteTrialReply] = None,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions___Literal[
            "get_current_timestamp",
            b"get_current_timestamp",
            "get_studies",
            b"get_studies",
            "get_trial",
            b"get_trial",
            "get_trials",
            b"get_trials",
            "reply",
            b"reply",
            "write_study",
            b"write_study",
            "write_trial",
            b"write_trial",
        ],
    ) -> builtin___bool: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal[
            "get_current_timestamp",
            b"get_current_timestamp",
            "get_studies",
            b"get_studies",
            "get_trial",
            b"get_trial",
            "get_trials",
            b"get_trials",
            "reply",
            b"reply",
            "write_study",
            b"write_study",
            "write_trial",
            b"write_trial",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing_extensions___Literal["reply", b"reply"]
    ) -> typing_extensions___Literal[
        "get_current_timestamp",
        "get_studies",
        "get_trials",
        "get_trial",
        "write_study",
        "write_trial",
    ]: ...

type___Reply = Reply

class GetCurrentTimestampRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    def __init__(
        self,
    ) -> None: ...

type___GetCurrentTimestampRequest = GetCurrentTimestampRequest

class GetCurrentTimestampReply(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    @property
    def timestamp(self) -> google___protobuf___timestamp_pb2___Timestamp: ...
    def __init__(
        self,
        *,
        timestamp: typing___Optional[google___protobuf___timestamp_pb2___Timestamp] = None,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions___Literal["timestamp", b"timestamp"]
    ) -> builtin___bool: ...
    def ClearField(
        self, field_name: typing_extensions___Literal["timestamp", b"timestamp"]
    ) -> None: ...

type___GetCurrentTimestampReply = GetCurrentTimestampReply

class GetStudiesRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    @property
    def timestamp(self) -> google___protobuf___timestamp_pb2___Timestamp: ...
    def __init__(
        self,
        *,
        timestamp: typing___Optional[google___protobuf___timestamp_pb2___Timestamp] = None,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions___Literal["timestamp", b"timestamp"]
    ) -> builtin___bool: ...
    def ClearField(
        self, field_name: typing_extensions___Literal["timestamp", b"timestamp"]
    ) -> None: ...

type___GetStudiesRequest = GetStudiesRequest

class GetStudiesReply(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    @property
    def studies(
        self,
    ) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[
        optur___proto___study_pb2___StudyInfo
    ]: ...
    def __init__(
        self,
        *,
        studies: typing___Optional[
            typing___Iterable[optur___proto___study_pb2___StudyInfo]
        ] = None,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions___Literal["studies", b"studies"]
    ) -> None: ...

type___GetStudiesReply = GetStudiesReply

class GetTrialsRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    @property
    def study_id(self) -> type___OptionalID: ...
    @property
    def timestamp(self) -> google___protobuf___timestamp_pb2___Timestamp: ...
    def __init__(
        self,
        *,
        study_id: typing___Optional[type___OptionalID] = None,
        timestamp: typing___Optional[google___protobuf___timestamp_pb2___Timestamp] = None,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions___Literal[
            "study_id", b"study_id", "timestamp", b"timestamp"
        ],
    ) -> builtin___bool: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal[
            "study_id", b"study_id", "timestamp", b"timestamp"
        ],
    ) -> None: ...

type___GetTrialsRequest = GetTrialsRequest

class GetTrialsReply(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    @property
    def trials(
        self,
    ) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[
        optur___proto___study_pb2___Trial
    ]: ...
    def __init__(
        self,
        *,
        trials: typing___Optional[typing___Iterable[optur___proto___study_pb2___Trial]] = None,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal["trials", b"trials"]) -> None: ...

type___GetTrialsReply = GetTrialsReply

class GetTrialRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    trial_id: typing___Text = ...
    @property
    def study_id(self) -> type___OptionalID: ...
    def __init__(
        self,
        *,
        trial_id: typing___Optional[typing___Text] = None,
        study_id: typing___Optional[type___OptionalID] = None,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions___Literal["study_id", b"study_id"]
    ) -> builtin___bool: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal["study_id", b"study_id", "trial_id", b"trial_id"],
    ) -> None: ...

type___GetTrialRequest = GetTrialRequest

class GetTrialReply(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    @property
    def trial(self) -> optur___proto___study_pb2___Trial: ...
    def __init__(
        self,
        *,
        trial: typing___Optional[optur___proto___study_pb2___Trial] = None,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions___Literal["trial", b"trial"]
    ) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal["trial", b"trial"]) -> None: ...

type___GetTrialReply = GetTrialReply

class WriteStudyRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    @property
    def study_info(self) -> optur___proto___study_pb2___StudyInfo: ...
    def __init__(
        self,
        *,
        study_info: typing___Optional[optur___proto___study_pb2___StudyInfo] = None,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions___Literal["study_info", b"study_info"]
    ) -> builtin___bool: ...
    def ClearField(
        self, field_name: typing_extensions___Literal["study_info", b"study_info"]
    ) -> None: ...

type___WriteStudyRequest = WriteStudyRequest

class WriteStudyReply(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    def __init__(
        self,
    ) -> None: ...

type___WriteStudyReply = WriteStudyReply

class WriteTrialRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    @property
    def trial(self) -> optur___proto___study_pb2___Trial: ...
    def __init__(
        self,
        *,
        trial: typing___Optional[optur___proto___study_pb2___Trial] = None,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions___Literal["trial", b"trial"]
    ) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal["trial", b"trial"]) -> None: ...

type___WriteTrialRequest = WriteTrialRequest

class WriteTrialReply(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    def __init__(
        self,
    ) -> None: ...

type___WriteTrialReply = WriteTrialReply

class OptionalID(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    string_value: typing___Text = ...
    def __init__(
        self,
        *,
        string_value: typing___Optional[typing___Text] = None,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions___Literal["string_value", b"string_value"]
    ) -> None: ...

type___OptionalID = OptionalID
