name: lint
on:
  push:
    branches:
      - main
  pull_request: {}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: install
        run: |
          python -m pip install -U pip
          pip install --progress-bar off -U black isort flake8 pyproject-flake8 mypy types-protobuf numpy "pytest>=6.2.5" pymysql types-pymysql pytest-timeout
      - name: black
        run: black . --check --diff
      - name: isort
        run: isort . --check --diff
      - name: flake8
        run: pflake8 .
      - name: mypy
        run: mypy .