name: lint
on:
  push:
    branches:
      - main
  pull_request: {}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: install protoc
        uses: arduino/setup-protoc@v1
      - name: install
        run: |
          python -m pip install -U pip
          pip install --progress-bar off -U black isort flake8 pyproject-flake8 mypy mypy-protobuf types-protobuf numpy "pytest>=6.2.5" pymysql types-pymysql pytest-timeout
      - name: compile proto
        run: |
          protoc optur/proto/*.proto --python_out=. --mypy_out=.
          black optur/proto
          isort optur/proto
      - name: black
        run: black . --check --diff
      - name: isort
        run: isort . --check --diff
      - name: flake8
        run: pflake8 .
      - name: mypy
        run: mypy .